// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bbb.proto

package bbb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the client's hello request
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbb_5b0c8256b91a483a, []int{0}
}
func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (dst *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(dst, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the server's response
type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbb_5b0c8256b91a483a, []int{1}
}
func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (dst *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(dst, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type BaseSystemEnvRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseSystemEnvRequest) Reset()         { *m = BaseSystemEnvRequest{} }
func (m *BaseSystemEnvRequest) String() string { return proto.CompactTextString(m) }
func (*BaseSystemEnvRequest) ProtoMessage()    {}
func (*BaseSystemEnvRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbb_5b0c8256b91a483a, []int{2}
}
func (m *BaseSystemEnvRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseSystemEnvRequest.Unmarshal(m, b)
}
func (m *BaseSystemEnvRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseSystemEnvRequest.Marshal(b, m, deterministic)
}
func (dst *BaseSystemEnvRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseSystemEnvRequest.Merge(dst, src)
}
func (m *BaseSystemEnvRequest) XXX_Size() int {
	return xxx_messageInfo_BaseSystemEnvRequest.Size(m)
}
func (m *BaseSystemEnvRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseSystemEnvRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BaseSystemEnvRequest proto.InternalMessageInfo

type BaseSystemEnvResponse struct {
	Network              string   `protobuf:"bytes,1,opt,name=Network,json=network,proto3" json:"Network,omitempty"`
	ElectrsRPCPort       string   `protobuf:"bytes,2,opt,name=ElectrsRPCPort,json=electrsRPCPort,proto3" json:"ElectrsRPCPort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseSystemEnvResponse) Reset()         { *m = BaseSystemEnvResponse{} }
func (m *BaseSystemEnvResponse) String() string { return proto.CompactTextString(m) }
func (*BaseSystemEnvResponse) ProtoMessage()    {}
func (*BaseSystemEnvResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bbb_5b0c8256b91a483a, []int{3}
}
func (m *BaseSystemEnvResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseSystemEnvResponse.Unmarshal(m, b)
}
func (m *BaseSystemEnvResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseSystemEnvResponse.Marshal(b, m, deterministic)
}
func (dst *BaseSystemEnvResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseSystemEnvResponse.Merge(dst, src)
}
func (m *BaseSystemEnvResponse) XXX_Size() int {
	return xxx_messageInfo_BaseSystemEnvResponse.Size(m)
}
func (m *BaseSystemEnvResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseSystemEnvResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BaseSystemEnvResponse proto.InternalMessageInfo

func (m *BaseSystemEnvResponse) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *BaseSystemEnvResponse) GetElectrsRPCPort() string {
	if m != nil {
		return m.ElectrsRPCPort
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "bbb.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "bbb.HelloReply")
	proto.RegisterType((*BaseSystemEnvRequest)(nil), "bbb.BaseSystemEnvRequest")
	proto.RegisterType((*BaseSystemEnvResponse)(nil), "bbb.BaseSystemEnvResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BitBoxBaseClient is the client API for BitBoxBase service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BitBoxBaseClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	// Get some relevant environment data from the base
	GetEnv(ctx context.Context, in *BaseSystemEnvRequest, opts ...grpc.CallOption) (*BaseSystemEnvResponse, error)
}

type bitBoxBaseClient struct {
	cc *grpc.ClientConn
}

func NewBitBoxBaseClient(cc *grpc.ClientConn) BitBoxBaseClient {
	return &bitBoxBaseClient{cc}
}

func (c *bitBoxBaseClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/bbb.BitBoxBase/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bitBoxBaseClient) GetEnv(ctx context.Context, in *BaseSystemEnvRequest, opts ...grpc.CallOption) (*BaseSystemEnvResponse, error) {
	out := new(BaseSystemEnvResponse)
	err := c.cc.Invoke(ctx, "/bbb.BitBoxBase/GetEnv", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BitBoxBaseServer is the server API for BitBoxBase service.
type BitBoxBaseServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	// Get some relevant environment data from the base
	GetEnv(context.Context, *BaseSystemEnvRequest) (*BaseSystemEnvResponse, error)
}

func RegisterBitBoxBaseServer(s *grpc.Server, srv BitBoxBaseServer) {
	s.RegisterService(&_BitBoxBase_serviceDesc, srv)
}

func _BitBoxBase_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BitBoxBaseServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bbb.BitBoxBase/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BitBoxBaseServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BitBoxBase_GetEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseSystemEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BitBoxBaseServer).GetEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bbb.BitBoxBase/GetEnv",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BitBoxBaseServer).GetEnv(ctx, req.(*BaseSystemEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BitBoxBase_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bbb.BitBoxBase",
	HandlerType: (*BitBoxBaseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _BitBoxBase_SayHello_Handler,
		},
		{
			MethodName: "GetEnv",
			Handler:    _BitBoxBase_GetEnv_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bbb.proto",
}

func init() { proto.RegisterFile("bbb.proto", fileDescriptor_bbb_5b0c8256b91a483a) }

var fileDescriptor_bbb_5b0c8256b91a483a = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x57, 0x95, 0xe9, 0x1e, 0x32, 0xf1, 0xa1, 0x52, 0x7b, 0x92, 0x1c, 0x86, 0xa7, 0x21,
	0xfa, 0x17, 0x58, 0x29, 0x7a, 0x92, 0xd1, 0x9d, 0x3c, 0x36, 0xf2, 0x10, 0x31, 0x4d, 0x62, 0xde,
	0x73, 0x9a, 0xa3, 0xff, 0xb9, 0x34, 0x5b, 0x61, 0x8e, 0xde, 0xf2, 0xfd, 0xc1, 0x37, 0xf9, 0x04,
	0x26, 0x5a, 0xeb, 0xb9, 0x0f, 0x4e, 0x1c, 0xee, 0x6b, 0xad, 0x95, 0x82, 0xe3, 0x27, 0x32, 0xc6,
	0xd5, 0xf4, 0xf9, 0x45, 0x2c, 0x88, 0x70, 0x60, 0x9b, 0x96, 0xf2, 0xec, 0x2a, 0xbb, 0x9e, 0xd4,
	0xe9, 0xac, 0x66, 0x00, 0x9b, 0x8e, 0x37, 0x11, 0x73, 0x38, 0x6c, 0x89, 0xb9, 0x79, 0xeb, 0x4b,
	0xbd, 0x54, 0x17, 0x70, 0x56, 0x36, 0x4c, 0xcb, 0xc8, 0x42, 0x6d, 0x65, 0x57, 0x9b, 0x4d, 0xf5,
	0x02, 0xe7, 0x3b, 0x3e, 0x7b, 0x67, 0x99, 0xba, 0xa9, 0x67, 0x92, 0x6f, 0x17, 0x3e, 0xfa, 0x29,
	0xbb, 0x96, 0x38, 0x83, 0x69, 0x65, 0xe8, 0x55, 0x02, 0xd7, 0x8b, 0x87, 0x85, 0x0b, 0x92, 0xef,
	0xa5, 0xc2, 0x94, 0xfe, 0xb9, 0xb7, 0xbf, 0x19, 0x40, 0xf9, 0x2e, 0xa5, 0xfb, 0xe9, 0x6e, 0xc0,
	0x1b, 0x38, 0x5a, 0x36, 0x31, 0x3d, 0x16, 0x4f, 0xe7, 0x1d, 0xea, 0x36, 0x5c, 0x71, 0xb2, 0x6d,
	0x79, 0x13, 0xd5, 0x08, 0xef, 0x61, 0xfc, 0x48, 0x52, 0xd9, 0x15, 0x5e, 0xa6, 0x70, 0x08, 0xa0,
	0x28, 0x86, 0xa2, 0x35, 0x83, 0x1a, 0xe9, 0x71, 0xfa, 0xce, 0xbb, 0xbf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x33, 0x26, 0x9f, 0x81, 0x5b, 0x01, 0x00, 0x00,
}
